# -*- coding: utf-8 -*-
"""ProjectPhase3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HgOW5EBQg2dO0nIiYbIIKsQSiNLFIEVZ
"""

from google.colab import files


uploaded = files.upload()

import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle

data = pd.read_csv('student-mat.csv', sep=";")

print(data.head())

data = data[["G1", "G2", "G3", "age", "Medu", "Fedu"]]

predict = "G3"

X = np.array(data.drop([predict], axis=1))
y = np.array(data[predict])

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.1)

linear = linear_model.LinearRegression()
linear.fit(x_train, y_train)
acc = linear.score(x_test, y_test)
print(acc)

print('Coefficient: \n', linear.coef_)
print('Intercept: \n', linear.intercept_)

predictions = linear.predict(x_test)

for x in range(len(predictions)):
    print(predictions[x], x_test[x], y_test[x])
